# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Software Engineering Lab"
subtitle: "Academic Year 2023"
logo: "/assets/images/ict_logo.png"
name: "Robert Songer"
email: rsonger@neptune.kanazawa-it.ac.jp
description: >- # this means to ignore newlines until "baseurl:"
  Course materials for the Software Engineering Lab class in the Science and 
  Technology Department at International College of Technology (ICT), Kanazawa.
github_username: rsonger
minimal_mistakes_skin: default
search: true
locale: "en-US"
repository: "rsonger/software-engineering-lab"
github: [metadata]

url: https://robsonger.dev # the base hostname & protocol for your site
baseurl: /software-engineering-lab # the subpath of your site, e.g. /blog/
last_updated: true # set to true if you want to display last updated in the footer

# Build settings
markdown: kramdown
kramdown:
  math_engine: katex
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: "Asia/Tokyo" # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

author:
  name   : "Robert Songer"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "Associate Professor teaching programming, web development, and software engineering at International College of Technology (ICT), Kanazawa."
  location: "Kanazawa, Japan"
  links:
    - 
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://robsonger.dev"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rsonger"
    - label: "ICT Home"
      icon: "fa fa-fw fa-school"
      url: "https://www.ict-kanazawa.ac.jp/"

atom_feed:
  hide: true

footer:
  links:
    - label: "ICT Home"
      icon: "fa fa-fw fa-school"
      url: "https://www.ict-kanazawa.ac.jp/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rsonger/software-engineering-lab"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      read_time: true

words_per_minute: 110

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

compress_html:
  clippings: all
  ignore:
    envs: development